TEKNOLABEL_TYPE_PASCAL = 0
TEKNOLABEL_TYPE_COCO = 1
TEKNOLABEL_TYPE_YOLO = 2

TEKNOLABEL_TRAINABLE_NAN = None
TEKNOLABEL_TRAINABLE_FALSE = False
TEKNOLABEL_TRAINABLE_TRUE = True

TEKNOLABEL_CLASSES_SINGLE_UAV = {"uav": 0}
TEKNOLABEL_CLASSES_DOUBLE_UAV_NONUAV = {"non-uav": 0, "uav": 1}
TEKNOLABEL_CLASSES_ULASIM = {"car":0, "kam":1, "ismak":2, "mot":3, "bus":4, "tren":5, "ins":6, "uyam":7, "yaam":8, "uuap":9, "yuap":10, "bis":11}

TCSU = TEKNOLABEL_CLASSES_SINGLE_UAV
TCDUN = TEKNOLABEL_CLASSES_DOUBLE_UAV_NONUAV
TCU = TEKNOLABEL_CLASSES_ULASIM

TEKNOLABEL_TYPES = {0: "Pascal VOC", 1: "Coco", 2: "Yolo"}
