TEKNOLABEL_TYPE_PASCAL = 0
TEKNOLABEL_TYPE_COCO = 1
TEKNOLABEL_TYPE_YOLO = 2

TEKNOLABEL_TRAINABLE_NAN = None
TEKNOLABEL_TRAINABLE_FALSE = False
TEKNOLABEL_TRAINABLE_TRUE = True

TEKNOLABEL_CLASSES_SINGLE_UAV = {"uav": 0}
TEKNOLABEL_CLASSES_DOUBLE_UAV_NONUAV = {"non-uav": 0, "uav": 1}

TEKNOLABEL_TYPES = {0: "Pascal VOC", 1: "Coco", 2: "Yolo"}
